# Generated by Django 5.1 on 2024-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_ventas', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_proveedores', models.CharField(max_length=100)),
                ('id_cliente', models.CharField(max_length=100)),
                ('id_empleado', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=1000)),
                ('precioventas', models.CharField(max_length=100)),
                ('fechaventas', models.DateField(max_length=100)),
                ('metodopago', models.CharField(max_length=100)),
            ],
        ),
    ]
