# Generated by Django 5.1 on 2024-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleados', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fechanacimientpo', models.DateField(max_length=100)),
                ('horario', models.CharField(max_length=1000)),
                ('sueldo', models.CharField(max_length=100)),
                ('numerotelefonico', models.CharField(max_length=100)),
            ],
        ),
    ]
