# Generated by Django 5.1.3 on 2024-11-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('aforo', models.CharField(max_length=1000)),
                ('numeroempleados', models.CharField(max_length=1000)),
            ],
        ),
    ]
