# Generated by Django 5.1 on 2024-11-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='id',
            new_name='id_cliente',
        ),
    ]
