# Generated by Django 5.1 on 2024-11-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_rename_id_materia_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='edad',
            field=models.CharField(max_length=100),
        ),
    ]
